#!/usr/bin/env python

import argparse

from gentoostats import list
from gentoostats import search

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--server', default='soc.dev.gentoo.org')
    parser.add_argument('-u', '--url', default='/gentoostats')

    subparsers = parser.add_subparsers()

    list.add_parser(subparsers)
    search.add_parser(subparsers)

    args = parser.parse_args()
    args.func(args)

if __name__ == "__main__":
    main()
