#!/usr/bin/env python

import sys
import importlib

actions = {
        'list': 'gentoostats.list',
        'search': 'gentooostats.search'
        }

def print_usage(actions):
    print 'Usage:', sys.argv[0], '<action>'
    print 'Available actions:'
    for action in actions.keys():
        print action

def main():
    argc = len(sys.argv)
    if argc == 1:
        print_usage(actions)
        sys.exit(1)
    try:
        loaded_module = importlib.import_module(actions[sys.argv[1]])
        loaded_module.main(opts=sys.argv[2:])
    except KeyError, ImportError:
        sys.stderr.writelines('Unknown action')
        sys.exit(1)


if __name__ == "__main__":
    main()
