#!/usr/bin/env python

from gentoostats.payload import Payload
import ConfigParser
import sys
import json
import urllib, httplib

def getAuthInfo():
  config = ConfigParser.ConfigParser()
  if len(config.read('/etc/gentoostats/auth.cfg')) == 0:
	sys.stderr.write('Cannot read auth.cfg')
	sys.exit(1)

  try:
	uuid = config.get('AUTH', 'UUID')
	passwd = config.get('AUTH', 'PASSWD')
	auth_info = {'UUID' : uuid, 'PASSWD' : passwd}
	return auth_info
  except (ConfigParser.NoSectionError, ConfigParser.NoOptionError):
	sys.stderr.write('Malformed auth.cfg')
	sys.exit(1)

def serialize(object, human=False):
  if human:
	indent = 2
	sort_keys = True
  else:
  	indent = None
	sort_keys = False
  return json.JSONEncoder(indent=indent, sort_keys=sort_keys).encode(object)

def main():
  pl = Payload()
  pl.dump(human=True)
  post_data = pl.get()
  post_data['AUTH'] = getAuthInfo()
  post_body = serialize(post_data,human=True)
  post_headers = {"Content-type": "application/json"}
  myuuid = getAuthInfo()['UUID']
  conn = httplib.HTTPConnection("127.0.0.1:8080")
  conn.request('POST', '/host/' + myuuid, headers=post_headers, body=post_body)
  #TODO: Handle exceptions
  response = conn.getresponse()
  print response.status, response.reason
  print 'Server response: ' + response.read()

if __name__ == "__main__":
  main()
